### ISSUE TITLE
感谢作者

### ISSUE THREAD

**Issue by eklim530** [scola/birthday#1]
感谢小软件帮大忙。
请问能否添加功能，使得日历能设置为全天事件。并增加不提醒的选项。
多谢。祝好。

**Comment by scola** [comment]
@eklim530 不客气，很高兴这个小软件能帮到你，全天事件这个有人提过
不提醒选项这个第一次有人提

你这个issue我留着吧，对这个功能需求的人多我就加上

**Comment by eklim530** [comment]
多谢回复~

**Comment by lcqbug** [comment]
eclipse 工程还是as 工程?怎么都倒不进来了?

**Comment by scola** [comment]
@lcqbug eclipse 工程

**Comment by scola** [comment]
@lcqbug 迁移到 as 工程了
