### ISSUE TITLE
岁数提醒能不能直接加在标题或者说明里

### ISSUE THREAD

**Issue by xjyfy** [scola/birthday#2]
TR。比如：XX的30岁生日，XX的31岁生日

**Comment by scola** [comment]
@xjyfy 可以, 农历生日的话, 每年都是一个独立的 event 比较简单, 
阳历生日连续N年都是一个event, 如果在标题中加入岁数的话, 每年的生日都是一个独立的 event

event 越多同步时间越长
如果这个需求的人多的话, 我考虑加上

**Comment by xjyfy** [comment]
@scola 我想您制作这个软件的初始目的或者寻找这样一个软件来解决问题的人，基本都是受困于农历生日提醒的问题。是不是可以添加一个开关来完成这个。

另外我今天使用的时候发现一个问题，每添加一个人，app就开始同步，这时接着添加一定会报一个错误。但是不影响使用
